### ISSUE TITLE
Swagger implementation 

### ISSUE THREAD

**Issue by CForrest97** [zowe/sample-node-api#2]
Add swagger annotations

**Comment by NakulManchanda** [comment]
didnt add annotations but added swagger.json

**Comment by NakulManchanda** [comment]
Swagger UI:
http://localhost:8080/api-docs-ui/

Swagger Doc:
http://localhost:8080/api-docs/

![image](https://user-images.githubusercontent.com/4791635/88351376-13078c80-cd24-11ea-9369-ad835555e121.png)
